EA-3496: Implement dead letter retry command; implement RabbitMQ queue listing via HTTP API
jtl-scx/channel-core pull request #52
Opened 2021-07-30 13:27 UTC by BrandtM

2021-08-04 13:48 UTC, sleipi requested changes
Bitte auch die Pipeline grün bekommen

2021-08-04 13:48 UTC, sleipi commented on src/Core/Command/DeadLetterRetryCommand.php
> +    protected static $defaultName = 'chn:dead-letter:retry';
Naming würde ich hier noch verbessern

Vorschlag 1
chn:message.retry

````
Available commands:
  help                                      Display help for a command
  list                                      List commands
 chn
  chn:message.consume                       Subscribe to all existing Event Queues and consume Messages from RabbitMQ
  chn:message.retry                         Moves messages from the Dead Letter queue back to their original queues
```` 

Vorschlag 2:
queue:dead-letter.retry

````
Available commands:
  help                                      Display help for a command
  list                                      List commands
 chn
  chn:message.consume                       Subscribe to all existing Event Queues and consume Messages from RabbitMQ
 db
  db:schema-up                              Migrate MongoDB Schema (run verbose to see index results)
 helper
  helper:emit.ChannelNotification           Helper command to emit Channel Notification with severity INFO
  // ...
 queue
  queue:dead-letter.retry                   Moves messages from the Dead Letter queue back to their original queues
 scx-api
  scx-api:get.events                        Consume seller events created from polling the SCX Channel API
````

In beiden Fällen würde es sich besser eingliedern

2021-08-04 13:48 UTC, sleipi commented on src/Core/Command/DeadLetterRetryCommand.php
> +        foreach ($queueList as $queue) {
Im Fall einer leeren queue list wäre es gut hier auch eine Ausgabe anzuzeigen.

````
No dead-letter queues found
````

2021-08-04 13:48 UTC, sleipi commented on src/Core/Command/DeadLetterRetryCommand.php
> +    private $olderThan;
type hints fehlen

generell würde ich diese filter und settings nicht als properties sehen, sondern lediglich den funktionen übergeben welche mit den Einstellungen arbeiten müssen.

2021-08-04 13:48 UTC, sleipi commented on src/Core/Command/DeadLetterRetryCommand.php
> +    private $olderThan;
Beipiel

`private function processQueue(string $queue, bool $interactive): void`

hier machst du es in teilen ja bereits mit $interactive

Vorschlag:
`private function processQueue(string $queue, bool $interactive, $olderThan, $filterBylastError, $resetReceives): void`

2021-08-04 13:48 UTC, sleipi commented on src/Core/Command/DeadLetterRetryCommand.php
> +                null,
pack ruhig noch ein shortcut hinzu :)

2021-08-04 13:48 UTC, sleipi commented on src/Core/Command/DeadLetterRetryCommand.php
> +                null,
pack ruhig noch ein shortcut hinzu :)

2021-08-04 13:48 UTC, sleipi commented on src/Core/Command/DeadLetterRetryCommand.php
> +    private function requeue(AMQPMessage $message): void
Gibt es hierfür nix fertiges?
Unser Emitter sollte doch genau die Funktionalität bieten die du brauchst?

2021-08-04 13:48 UTC, sleipi commented on src/Core/Amqp/RabbitMqQueueLister.php
> +        curl_setopt_array($curlHandle, [
Was spricht hier gegen die Verwendung von Guzzle? Im Core ist es bestandteil des Composer JSON

2021-08-04 13:48 UTC, sleipi commented on src/Core/Amqp/RabbitMqQueueLister.php
> +    public function listQueues(string $queuePrefix = null): array
Wie sehen die Daten aus die hier zurück kommen? 

Nur ein string dann pack die Beschreibung der Array Struktur als docblock in den Header
````
@return array<int, string>
````

2021-08-04 13:48 UTC, sleipi commented on src/Core/Amqp/RabbitMqQueueLister.php
> +namespace JTL\SCX\Lib\Channel\Core\Amqp;
Vorschlag: JTL\SCX\Lib\Channel\Core\RabbitMqManagementApi

2021-08-10 09:56 UTC, BrandtM commented on src/Core/Command/DeadLetterRetryCommand.php
> +    private function requeue(AMQPMessage $message): void
Ich hab hier nichts passendes gefunden. Der Emitter kann z. B. nicht den Routing Key der Message ändern; ich hab den Code also erstmal so gelassen.

2021-08-16 08:51 UTC, sleipi commented on src/Core/Command/DeadLetterRetryCommand.php
> +        foreach ($queueList as $queue) {
@BrandtM - was ist hiermit? Hattest du dich dazu entschieden kein Log einzubauen? oder fehlt ggf. ein Commit?

2021-08-19 09:22 UTC, BrandtM commented on src/Core/Command/DeadLetterRetryCommand.php
> +        foreach ($queueList as $queue) {
@sleipi Da fehlt nix. Ich hab das doch schon behoben?

2021-08-25 10:38 UTC, merged